import React from 'react';
import type { Metadata } from 'next';
import ClientApolloProvider from './providers/ClientApolloProvider';
import "styles/globals.css";

export const metadata: Metadata = {
  title: "Soul Bonding",
  description: "Generated by Tannehill on earth",
};

const RootLayout: React.FC<{children: React.ReactNode }> = ({
  children,
})=> {
  return (
    <html lang="en">
      <body>
        <ClientApolloProvider>
          {children}
        </ClientApolloProvider>
      </body>
    </html>
  );
};

export default RootLayout;