// "use client";
import type { Metadata } from 'next';
import ClientApolloProvider from './providers/ClientApolloProvider';
import "./globals.css";

export const metadata: Metadata = {
  title: "Soul Bonding",
  description: "Generated by Tannehill on earth",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <ClientApolloProvider>
          {children}
        </ClientApolloProvider>
      </body>
    </html>
  );
};